Feat/add pivot link
polarityio/exabeam pull request #8
Opened 2023-11-30 23:32 UTC by ntsmith7

2023-11-30 23:35 UTC, ntsmith7 commented
NOTES FOR REVIEWER: 

- Add an external pivot link to Exabeam platform 
- Add a user option that allows for the instance url to be used for the pivot link, as the API URL is different. 
- Add a minimum of 6 characters to regex

2024-01-02 22:00 UTC, sarus requested changes

2024-01-02 22:00 UTC, sarus commented on templates/template.hbs
> +    <a class="p-link" href="{{block.userOptions.instanceUrl}}">Go To Exabeam</a>
@ntsmith7 Can this pivot link take the user to the their search results?

2024-01-02 22:06 UTC, ntsmith7 commented on templates/template.hbs
> +    <a class="p-link" href="{{block.userOptions.instanceUrl}}">Go To Exabeam</a>
If I remember correctly, I don't think so - as that is what I was initially wanted to do. I went to go check again, but the creds are now allowing me in the dashboard.

2024-12-11 02:14 UTC, closed without merging